name: zealth_assignment
description: Frontend Interview Assignment-Zealth
authors:
  - Divyanshu Sahu
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  http: 0.13.4
  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  connectivity: ^3.0.6
  url_launcher: ^6.0.2
  url_launcher_web: ^2.0.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/pp.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

  uses-material-design: true
